### ISSUE TITLE
Cutout

### ISSUE THREAD

**Issue by markagustine221** [Matsuo3rd/sms-forward#2]
is possible to modify this project to be a cutout?
for example we have these:
*Sender 1
*Sender 2
*Cutout
*Owner
When Sender 1 send message to Cutout it will automatically forwarded the message to Owner and when Owner reply to Cutout will also forwarded to  Sender 1. Same as Sender 2.

**Comment by Matsuo3rd** [comment]
The use case described can be implemented using SMS API delivered by Huawei Dongle and some routing heuristic.
You can get inspiration from this project codebase. However, this use case won't be part of this project core feature.
