### ISSUE TITLE
Supported Huawei Dongles

### ISSUE THREAD

**Issue by kenshin171** [Matsuo3rd/sms-forward#3]
Sorry if this is not the right forum for questions. 
I have 2 Huawei dongles Model numbers E5331 and E5573C.
Do any of these work with this sms-forward application?

**Comment by Matsuo3rd** [comment]
Those dongles **shall** work. Please report back if you are successful.

**Comment by kenshin171** [comment]
sorry for the late response, and good news, yes E5331 is working! Have not tried E5573C yet though. Will report back when i do. Thanks for this useful app!

**Comment by Matsuo3rd** [comment]
Thanks for the update!
